### ISSUE TITLE
Error bzip2 1.0.6 tar archive

### ISSUE THREAD

**Issue by BarviX6** [Duckbox-Developers/buildsystem-ddt#1]
wget --no-check-certificate -t6 -T20 -c -P /home/barvix/Archive http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz
--2018-08-19 14:02:00--  http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz
Resolving www.bzip.org (www.bzip.org)... 208.91.197.44
Connecting to www.bzip.org (www.bzip.org)|208.91.197.44|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 271 [text/html]
Saving to: '/home/barvix/Archive/bzip2-1.0.6.tar.gz'

bzip2-1.0.6.tar.gz  100%[===================>]     271  --.-KB/s    in 0s      

2018-08-19 14:02:01 (24.9 MB/s) - '/home/barvix/Archive/bzip2-1.0.6.tar.gz' saved [271/271]
==============================================================

Start build of bzip2 1.0.6
rm -rf /home/barvix/buildsystem-ddt/build_tmp/bzip2-1.0.6
tar -C /home/barvix/buildsystem-ddt/build_tmp -xf /home/barvix/Archive/bzip2-1.0.6.tar.gz
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
make/contrib-libs.mk:634: ошибка выполнения рецепта для цели «/home/barvix/buildsystem-ddt/.deps/bzip2»
make: *** [/home/barvix/buildsystem-ddt/.deps/bzip2] Ошибка 2

**Comment by BPanther** [comment]
As you can see

tar: This does not look like a tar archive
gzip: stdin: not in gzip format

The archive is wrong. Just delete and try again.

**Comment by vuteam** [comment]
hello 

please you can add vu+ solo2 Machine i want to test this great image

thank you

**Comment by BPanther** [comment]
Has nothing to do with the bzip error.

But not possible, because mips cpu and nothing for mips (and currently not planned) at the git.

**Comment by vuteam** [comment]
i have added the mipsel by my slef Ok and i have build Neutrino for Vu+
sol2 hhhhhhhhhhhh

**Comment by TangoCash** [comment]
Can you make a pull request, to merge the changes into our git ?

**Comment by vuteam** [comment]
the image under a test
