### ISSUE TITLE
OpenThreads Paket Source nicht mehr verfügbar

### ISSUE THREAD

**Issue by Ezak91** [Duckbox-Developers/buildsystem-ddt#16]
Build baut nicht mehr von vorne durch

--2017-11-28 01:28:02--  https://trac.openscenegraph.org/downloads/developer_releases/OpenThreads-2.6.0.zip
Resolving trac.openscenegraph.org (trac.openscenegraph.org)... 158.42.9.50
Connecting to trac.openscenegraph.org (trac.openscenegraph.org)|158.42.9.50|:443... failed: Connection refused.
make: *** [/root/Archive/OpenThreads-2.6.0.zip] Error 4

**Comment by MaxWiesel** [comment]
libopenthreads wurde, am 18.11.2017 in eine neue Version geändert.

https://github.com/Duckbox-Developers/buildsystem-ddt/commit/bf775c764adee49e517117e313e1073fb45f9af3

im BS Ordner einmal make update ausführen, damit alles aktualisiert wird.

**Comment by Ezak91** [comment]
Sorry mein Fehler, merge hat nicht funktioniert -.-
