### ISSUE TITLE
Undefined reference when building libsoup

### ISSUE THREAD

**Issue by ph4nt0m** [Duckbox-Developers/buildsystem-ddt#2]
I'm trying to `make neutrino-mp` under Ubuntu 19.04, but there is a linking error when trying to build `libsoup`:
```
../libsoup/.libs/libsoup-2.4.so: undefined reference to `xmlNewChild'
../libsoup/.libs/libsoup-2.4.so: undefined reference ../libsoup/.libs/libsoup-2.4.so: undefined reference to `xmlNewChild'
../libsoup/.tolibs /`libsoupxmlParseMemory-'2.4.so
:. .undefined/ libsoupreference/ .tolibs /`libsoupxmlParseMemory-'2.4.so
:. .undefined/ libsoupreference/ .tolibs /`libsoupxmlDocDumpMemory-2.4.so: undefined reference to `xmlDocDumpMemory'
../libsoup/.libs/libsoup-2.4.so':
 .undefined. /referencelibsoup /to. libs`/xmlNewTextChildlibsoup'-
2.4.so.:. /undefinedlibsoup /reference. libsto/ libsoup`-xmlNewTextChild2.4.so':
 .undefined. /referencelibsoup /to.libs /`libsoupxmlDocSetRootElement-'2.4.so
:collect2: error: ld returned 1 exit status
 undefined reference to `xmlDocSetRootElement'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:424: simple-proxy] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [Makefile:420: simple-httpd] Error 1
../libsoup/.libs/libsoup-2.4.so: undefined reference to `xmlNewChild'
../libsoup/.libs/libsoup-2.4.so: undefined reference to `xmlParseMemory'
../libsoup/.libs/libsoup-2.4.so: undefined reference to `xmlDocDumpMemory'
../libsoup/.libs/libsoup-2.4.so: undefined reference to `xmlNewTextChild'
../libsoup/.libs/libsoup-2.4.so: undefined reference to `xmlDocSetRootElement'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:416: get] Error 1
make[2]: *** [Makefile:539: all-recursive] Error 1
make[1]: *** [Makefile:443: all] Error 2
```
`libxml2` built fine and is located in `buildsystem-ddt/tufsbox/cdkroot/usr/lib`, so I don't know why `libsoup` fails to link against it.

**Comment by BPanther** [comment]
You should write what exactly (all make.sh parameter) you try to build, not only the error message. I build here UFS910, UFS912, UFS913, UFS922, AV700, AV7000, AV7500, Pingulux, Cube, Mini2, Cube 3000HD, HD51, Solo4K, Duo4K with Ubuntu 18.04.2 LTS (x64,Kernel 4.15.0-51) without problems.

**Comment by ph4nt0m** [comment]
@BPanther I'm trying to build for Spark, more precisely I used the following options when calling `make.sh`:

- 27\) Spark
- 2\) STM 24 P0217 [2.6.32.71]
- 1\) optimization for size
- 2\) gstreamer
- 1\) Neutrino
- 1\) neutrino-mp-ddt    [ arm/sh4 ]
- 1\) No external LCD

After that, `make neutrino-mp` fails with the above error.

**Comment by BPanther** [comment]
Ah, gstreamer - why not libeplayer3 (buildinplayer)? gstreamer long time not testet anymore...

EDIT: You can try a newer version of libsoup (2.67.2) - maybe this works but not testet.

**Comment by ph4nt0m** [comment]
Good to know, I didn't find that in the docs. Building with `libeplayer3` worked straight away.

I tried version 2.65.1 (after that, they changed the buildsystem) which required to build `libpsl` first, but after all, I still get the same linkage errors to some `libxml2` symbols.

**Comment by ph4nt0m** [comment]
@BPanther I found the reason: For sh4, `libxml2` is configured `--with-minimum`. This disables `tree`, `sax1` and `output`, which are required by `libsoup`.

I can create a pull request if you want.

**Comment by BPanther** [comment]
The "minimum" is required for receiver without enough flash (e.g. UFS910/22). And because "nobody" use the gstreamer there was no problem. Maybe we can change this soon for some receiver.

**Comment by ph4nt0m** [comment]
I didn't mean to remove the `--with-minimum` completely. Instead, you can selectively add back only the three missing modules by appending `--with-tree` and so on. This should still save some space compared to a full build of `libxml2`.

I'm closing this issue now since it's resolved for me, the pull request was just an offer from my side, but if nobody is interested in gstreamer, that's totally fine. :)
